import React from 'react';
import EditorProductRow from './EditorProductRow';
import { Icons } from './Icons';
import '../styles/dashboard.css';

// The main Dashboard component where the user inputs bill details.
// It receives state and handler functions from the parent component (App.js) to manage data.
export default function Dashboard({ 
  billData, 
  handleDataChange, 
  items, 
  updateItem, 
  removeItem, 
  addItem, 
  productCatalog, 
  onGenerate 
}) {
  return (
    <>
      {/* HEADER SECTION: Displays the dashboard title and icon */}
      <div className="editor-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{fontSize:'24px'}}><Icons.Dashboard /></div>
          <h2>Billing Dashboard</h2>
        </div>
      </div>

      {/* CONTENT SECTION: Contains the forms for Client, Invoice, and Products */}
      <div className="editor-content">
        
        {/* 1. Client Details Section: Inputs for Name, Mobile, and Address */}
        <div className="form-group">
          <div className="form-section-title">Client Details</div>
          <div className="input-grid">
            <input 
              name="clientName" 
              placeholder="Enter Client Name" 
              value={billData.clientName} 
              onChange={handleDataChange} 
            />
            <input 
              name="clientMobile" 
              placeholder="Enter Mobile Number" 
              value={billData.clientMobile} 
              onChange={handleDataChange} 
            />
          </div>
          <div style={{marginTop: '12px'}}>
            <input 
              name="clientAddress" 
              placeholder="Enter Client Address / Place" 
              value={billData.clientAddress} 
              onChange={handleDataChange} 
            />
          </div>
        </div>

        {/* 2. Invoice Details Section: Inputs for Date and Read-Only Bill Number */}
        <div className="form-group">
          <div className="form-section-title">Invoice Details</div>
          <div className="input-grid">
            <div>
              <label style={{fontSize:'12px', color:'#64748b', display:'block', marginBottom:'5px'}}>Date</label>
              <input type="date" name="billDate" value={billData.billDate} onChange={handleDataChange} />
            </div>
            <div>
              <label style={{fontSize:'12px', color:'#64748b', display:'block', marginBottom:'5px'}}>Bill No</label>
              {/* Read-only field because Bill No is auto-generated by the backend */}
              <input name="billNo" value={billData.billNo} readOnly style={{background:'#f1f5f9', color:'#64748b'}} />
            </div>
          </div>
        </div>

        {/* 3. Products List Section: Dynamic list of product rows */}
        <div className="form-group">
          <div className="form-section-title">Products List</div>
          {/* Loop through the 'items' array and render a row for each product */}
          {items.map((item, index) => (
            <EditorProductRow 
              key={index}
              index={index}
              item={item}
              updateItem={updateItem}
              removeItem={removeItem}
              productCatalog={productCatalog}
            />
          ))}
          
          {/* Button to add a new empty row to the product list */}
          <button className="btn-add" onClick={addItem}>
            <Icons.Plus /> Add New Item
          </button>
        </div>
      </div>

      {/* FOOTER SECTION: The primary action button to save/generate the bill */}
      <div className="editor-footer">
        <button className="btn-primary" onClick={onGenerate}>
          <Icons.Check /> Generate Bill
        </button>
      </div>
    </>
  );
}